spring.application.name=study-assistant
spring.datasource.url=jdbc:mysql://localhost:3306/studyassistant
spring.datasource.username=root
spring.datasource.password=sqlpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true